# Error code constants — used by set_error() call sites and Phase 5 UI mapping
DOCLING_TIMEOUT = "DOCLING_TIMEOUT"
DOCLING_PARSE_ERROR = "DOCLING_PARSE_ERROR"
GEMINI_ERROR = "GEMINI_ERROR"
INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
